name: Manual Approval Workflow

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: 'Nom du bucket S3'
        required: true
      file_path:
        description: 'Chemin du fichier dans le bucket S3'
        required: true

env:
  Week: |
    Monday: 1
    Tuesday: 2
    Wednesday: 3
    Thursday: 4
    Friday: 5


jobs:

  main-job:
    runs-on: ubuntu-latest
    environment: rm_last_used_version
    steps:

      - name: Afficher les détails de l'objet S3-${{ github.event.inputs.bucket }}/${{ github.event.inputs.file_path }}
        run: |
          echo "Approuved"
          echo ${{ env.week }}
