name: Manual Approval Workflow

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: 'Nom du bucket S3'
        required: true
      file_path:
        description: 'Chemin du fichier dans le bucket S3'
        required: true

jobs:
  wait-for-approval:
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.approve.outputs.approved }}
    steps:
      - name: Demande d'approbation
        id: approve
        run: |
          echo "::notice::En attente d'approbation. Veuillez approuver manuellement."
          sleep 30  # Ajoute un délai d'attente manuel pour faciliter l'approbation


  main-job:
    runs-on: ubuntu-latest
    needs: wait-for-approval
    if: needs.wait-for-approval.result == 'success'
    steps:

      - name: Afficher les détails de l'objet S3
        run: |
          echo "Approuved"